version: '3.3'
services:
    jaeger-all-in-one:
        container_name: jaeger
        image: 'jaegertracing/all-in-one:1.46'
        environment:
            - COLLECTOR_OTLP_ENABLED=true
            - 'COLLECTOR_ZIPKIN_HOST_PORT=:9411'
        ports:
            - '5775:5775/udp'
            - '6831:6831/udp'
            - '6832:6832/udp'
            - '5778:5778'
            - '16686:16686'
            - '14250:14250'
            - '14268:14268'
            - '14269:14269'
            - '4317:4317'
            - '4318:4318'
            - '9411:9411'