// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.0
// source: copyfrom.go

package db

import (
	"context"
)

// iteratorForSessionJoinsConversationUseCopyFrom implements pgx.CopyFromSource.
type iteratorForSessionJoinsConversationUseCopyFrom struct {
	rows                 []SessionJoinsConversationUseCopyFromParams
	skippedFirstNextCall bool
}

func (r *iteratorForSessionJoinsConversationUseCopyFrom) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForSessionJoinsConversationUseCopyFrom) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].SessionID,
		r.rows[0].ConversationID,
	}, nil
}

func (r iteratorForSessionJoinsConversationUseCopyFrom) Err() error {
	return nil
}

func (q *Queries) SessionJoinsConversationUseCopyFrom(ctx context.Context, arg []SessionJoinsConversationUseCopyFromParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"public", "conversation_session_id"}, []string{"session_id", "conversation_id"}, &iteratorForSessionJoinsConversationUseCopyFrom{rows: arg})
}
