// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: copyfrom.go

package db

import (
	"context"
)

// iteratorForSessionJoinsConvercationUseCopyFrom implements pgx.CopyFromSource.
type iteratorForSessionJoinsConvercationUseCopyFrom struct {
	rows                 []SessionJoinsConvercationUseCopyFromParams
	skippedFirstNextCall bool
}

func (r *iteratorForSessionJoinsConvercationUseCopyFrom) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForSessionJoinsConvercationUseCopyFrom) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].SessionID,
		r.rows[0].ConvercationID,
	}, nil
}

func (r iteratorForSessionJoinsConvercationUseCopyFrom) Err() error {
	return nil
}

func (q *Queries) SessionJoinsConvercationUseCopyFrom(ctx context.Context, arg []SessionJoinsConvercationUseCopyFromParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"public", "conversation_session_id"}, []string{"session_id", "convercation_id"}, &iteratorForSessionJoinsConvercationUseCopyFrom{rows: arg})
}
