// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Conversation struct {
	ConversationID   pgtype.UUID
	LastMsgID        pgtype.Text
	LastSendTime     string
	IsDelete         bool
	ConversationType int32
	LastSendSession  string
}

type ConversationSessionID struct {
	ID             int32
	SessionID      int32
	LastRecvMsgID  pgtype.Text
	IsKickOut      bool
	ConvercationID pgtype.UUID
}

type Message struct {
	MsgID          string
	ConvercationID pgtype.UUID
	FromSession    int32
	SendTime       pgtype.Timestamp
	Status         int32
	Type           int32
	Content        pgtype.Text
}

type Session struct {
	ID      int32
	Session string
}
