// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
	jtime "github.com/quick-im/quick-im-core/internal/jtime"
)

type Conversation struct {
	ConversationID   string
	LastMsgID        *string
	LastSendTime     pgtype.Timestamp
	IsDelete         bool
	ConversationType int64
	LastSendSession  *string
	IsArchive        bool
}

type ConversationSessionID struct {
	ID             int32
	SessionID      string
	LastRecvMsgID  *string
	IsKickOut      bool
	ConversationID string
}

type Message struct {
	MsgID          string
	ConversationID string
	FromSession    int32
	SendTime       jtime.Time
	Status         int32
	Type           int32
	Content        *string
}

type Session struct {
	ID      int32
	Session string
}
