// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getConvercationSessionCountByConvercationPkId = `-- name: GetConvercationSessionCountByConvercationPkId :one
SELECT count(id) FROM conversation_session_id
WHERE convercation_id = $1::uuid
`

func (q *Queries) GetConvercationSessionCountByConvercationPkId(ctx context.Context, convercationID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getConvercationSessionCountByConvercationPkId, convercationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}
